### ISSUE TITLE
Clarification of license?

### ISSUE THREAD

**Issue by fasiha** [alecjacobson/gptoolbox#22]
Thanks for making this! But I’m confused by the wording at https://github.com/alecjacobson/gptoolbox#license because it doesn’t list a license. All published code is copyrighted by someone or something, whether its MPL2 or BSD or GPL licensed, right? So what‘s the license right now? (I.e., specific questions someone might have include, “if I make changes to this, do I have to share them with upstream?” Also, “Can I use this at work?”)

**Comment by alecjacobson** [comment]
I was conservative originally because I had a mixture of my own code and
others. I will update and clarify this, but the basic message is that
original code is under MPL2. Possible exceptions are anything in the
`external/` and `wrappers` folders and some code in the `mex/` folder
depends on external libraries like CGAL that have more copyleft licenses.
